#!/usr/bin/env bash

#node pathfinder.js "$@"

function tp() {
    result=$(node pathfinder.js "$@")

    if [[ $result == *"Locations stored in DB:"* ]]; then
        echo $result
    elif [[ $result == *"/home/"* ]]; then
        echo "result contains /home/"
        #echo $result
    else
        echo $result
    fi
}
