#!/usr/bin/env bash
function tp() {
    result=$( node ~/.scripts/pathfinder.js "$@")
    if [[ $result == *"Locations stored in DB:"* ]]; then
        echo $result
    elif [ -d "$result" ]; then
        cd $result
    elif [ ! -z "$result" ]; then
        echo $result
    else
    fi
}
